### ISSUE TITLE
`tree-sitter generate` fails on current master

### ISSUE THREAD

**Issue by ahumenberger** [tree-sitter/tree-sitter-java#141]
Revision [87e6419](https://github.com/tree-sitter/tree-sitter-java/commit/87e6419a74a9dbaf8f2a5a57b86b733bdda381f5)

```
[stdin]:191
      throw value
      ^

ReferenceError: Undefined symbol 'text_block'
    at Object.get ([stdin]:209:23)
    at Proxy._literal (/home/andreas/repos/tree-sitter-java/grammar.js:94:9)
    at grammar ([stdin]:283:42)
    at Object.<anonymous> (/home/andreas/repos/tree-sitter-java/grammar.js:30:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18) {
  symbol: { type: 'SYMBOL', name: 'text_block' }
}
Node process exited with status 1
```

**Comment by ahumenberger** [comment]
It seems as `text_block` got removed in favor of `_multiline_string_literal` in #137. Added fix to #139. I hope that's correct.

**Comment by amaanq** [comment]
oof, really sorry about that. should've double checked tree-sitter generate in my last change in that pr

**Comment by ahumenberger** [comment]
> should've double checked tree-sitter generate in my last change in that pr

The CI should make sure that something like that does not happen.

**Comment by zimmski** [comment]
@ahumenberger since we are now committed to this project, could you do that change please?

**Comment by amaanq** [comment]
> > should've double checked tree-sitter generate in my last change in that pr
> 
> The CI should make sure that something like that does not happen.

it did, but then I made a couple of changes by force pushing and the CI has to be run by a maintainer again.
